### ISSUE TITLE
As a user I can't create an email account

### ISSUE THREAD

**Issue by SailfishDeveloper** [nemomobile-ux/glacier-mail#1]
Instructions for reproduction:

1. Tab on the Plus symbol
2. Tab on "Other" (for example)
3. Enter account name and credentials
4. Tab on "Next"
5. Enter server settings
6. Tab "Next"
7. Nothing happens

[glacier-mail log.txt](https://github.com/nemomobile-ux/glacier-mail/files/3025652/glacier-mail.log.txt)

I tried to modify line 239 in ManualScreen.qml with `manualSettingsPage.state = "DetailsScreen";` with no impact. Only the last error of the log disappears.

**Comment by neochapay** [comment]
fixed
